services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: advertisement
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-boot-network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  spring-boot-app:
    container_name: online-advertising
    image: souhirjdidi/online-advertising:latest
    ports:
      - "8088:8080"
    networks:
      - spring-boot-network
    depends_on:
      - postgres

volumes:
  postgres:
networks:
  spring-boot-network:
    driver: bridge

